language: node_js
node_js:
  - stable
services:
  - mongodb
install:
  - npm install
before_script:
  - mkdir ../Secret
  - echo "asdf" > ../Secret/devdoodleDB.key
  - mongo DevDoodle --eval 'db.addUser({user:"DevDoodle",pwd:"asdf",roles:["readWrite"]});'
script: node server 8080 --nossl