language: node_js
node_js:
  - stable
services:
  - mongodb
install:
  - npm install
before_script:
  - mkdir ../Secret
  - echo "asdf" > ../Secret/devdoodleDB.key
  - mongo mydb_test --eval 'db.addUser({user:"DevDoodle",pwd:"asdf",roles:[{role:"readWrite",db:"DevDoodle"}]});'
script: node server 8080 --nossl