language: node_js
node_js:
  - stable
services:
  - mongodb
install:
  - npm install
  - npm install -g nsp
  - npm install -g eslint
  - npm install -g stylelint
script:
  - npm test
  - eslint ./
  - stylelint ./*/*.css ./*/*/*.css -f verbose
